[package]
name = "bitcoin-capnp"
description = "A Rust client library for Bitcoin Core's Capnp (inter-process communication) interface"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Johnny Santos"]
homepage = "https://stratumprotocol.org"
keywords = ["bitcoin", "bitcoin-core", "mining", "stratum"]

[dependencies]
bitcoin = "0.32.7"
capnp = "0.21.7"
capnp-rpc = "0.21.0"
thiserror = "2"
tokio = {
  version = "1.44.1",
  features = [
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "time"
  ]
}
tokio-util = { version = "0.7.10", features = ["compat"] }
tracing = "0.1.41"

[dev-dependencies]
tracing-subscriber = "0.3.19"

[build-dependencies]
capnpc = "0.21.2"
